---
title: "Assignment1"
author: "Henghui Qi"
date: "2022/5/15"
output: html_document
---

```{r}
library(lubridate)
library(timeDate)

get.hours = function(iso, peak.type, period){
  #process date
  l = nchar(period)#length of the string period
  if(is.na(as.numeric(substr(period,1,4)))){stop("wrong input of period")}
  Year = as.numeric(substr(period,1,4))
  if(l==5){#annually
    Year = as.numeric(substr(period,1,4))
    start.date = ymd(paste0(Year,"0101"))
    end.date = ymd(paste0(Year,"1231"))
    
  }else if(l==6){#quarterly
    Year = as.numeric(substr(period,1,4))
    Quarter = as.numeric(substr(period,6,6))
    start_month = 3*(Quarter-1) + 1
    end_month = start_month + 2
    start.date = ymd(paste0(Year,month.name[start_month],"01"))
    end.date = ymd(paste0(Year,month.name[end_month],"01"))%m+% months(1)%m-% days(1)
    
  }else if(l==7){#monthly
    Year = as.numeric(substr(period,1,4))
    Month = which(month.abb==substr(period,5,7))
    start.date = ymd(paste0(Year,month.name[Month],"01"))
    end.date = ymd(paste0(Year,month.name[Month],"01"))%m+% months(1)%m-% days(1)

  }else if(l>7&&l<11){#daily
    period = ymd(period)
    Year = year(period)
    Month = month(period)
    Day = day(period)
    start.date = period
    end.date = period
  }else {stop("wrong input of period")}
  
  #____________________________________________________
  #process peak type 
  include = 0#whether this kind of peak type take daylight-saving into consideration
  days = seq(start.date, end.date, by = "days")
  if(peak.type == "flat"){
    include = 1
    hours = length(days)*24
    
  }else if(peak.type=="7x8"){
    include = 1
    hours = length(days)*16
    
  }else{
    interval = interval(start.date, end.date)
    weekdays = wday(days)
    year_holidays = as.Date(holidayNERC(Year))
    holidays = year_holidays[year_holidays%within%interval]
    non_holidays = days[!days%in%holidays]
    
    #process ISO
    if(iso %in% c("PJMISO", "MISO", "ERCOT", "SPPISO", "NYISO")){#Eastern market
      weekend = c(1,7)
    }else if(iso %in% c("WECC", "CAISO")){#Western market
      weekend = 1
    }else {stop("wrong input of iso")} 
    
    non_holiday_weekdays =
      non_holidays[non_holidays%in%days[!weekdays%in%weekend]]
    if(peak.type=="onpeak"){
      hours = length(non_holiday_weekdays)*16
    }else if(peak.type=="offpeak"){
      include = 1
      hours = length(days)*24 - length(non_holiday_weekdays)*16
    }else if(peak.type=="2x16H"){
      hours = length(unique(c(days[weekdays%in%weekend], holidays)))*16
    }else {stop("wrong input of peak.type")}
  }
  
  if(iso!="MISO"&&include==1){#daylight-saving setting
    march = seq(ymd(paste0(Year, "0301")), ymd(paste0(Year, "0331")), by = "day")
    mar_weekdays = wday(march)
    if(march[mar_weekdays==1][2]%in%days){hours = hours - 1}#it begins at 2:00 a.m. on the second Sunday of March
    november = seq(ymd(paste0(Year, "1101")), ymd(paste0(Year, "1130")), by = "day")
    nov_weekdays = wday(november)
    if(november[nov_weekdays==1][1]%in%days){hours = hours + 1}#it ends at 2:00 a.m. on the first Sunday of November
  }
        
  #____________________________________________________
  #present the result
  result = list(iso = iso, 
                peak.type = peak.type,
                start.date = start.date,
                end.date = end.date,
                num.hour = hours)
  return(result)
}
```

```{r, error=TRUE}
# test the type of the return
num.hours.ercot.onpeak.may19 <- get.hours("ERCOT", "onpeak", "2019May")
num.hours.ercot.onpeak.may19

# test wrong input situation
get.hours("wrong", "onpeak", "2019May")
get.hours("ERCOT", "wrong", "2019May")
get.hours("ERCOT", "onpeak", "wrong")

# test CAISO of 2022 to 2024
## monthly
peaktype = c("flat", "onpeak", "offpeak")
CAISO_calender_monthly = data.frame(Month = month.abb,
                                    Year = rep(2022:2024, each = 12),
                                    flat = 0,
                                    onpeak = 0,
                                    offpeak = 0)
for(y in 1:3){
  for(i in 1:12){
    period = paste0(y+2022-1, month.abb[i])
    for(j in 1:3){
      peak = peaktype[j]
      result = get.hours("CAISO", peak, period)
      CAISO_calender_monthly[(y-1)*12+i, j+2] = result$num.hour
      }
    }
}
print(CAISO_calender_monthly)

## Quarterly
CAISO_calender_quarterly = data.frame(Quarter = rep(paste0("Q",1:4), 3),
                                    Year = rep(2022:2024, each = 4),
                                    flat = 0,
                                    onpeak = 0,
                                    offpeak = 0)
for(y in 1:3){
  for(i in 1:4){
    period = paste0(y+2022-1, paste0("Q",i))
    for(j in 1:3){
      peak = peaktype[j]
      result = get.hours("CAISO", peak, period)
      CAISO_calender_quarterly[(y-1)*4+i, j+2] = result$num.hour
      }
    }
}
print(CAISO_calender_quarterly)

## Yearly
CAISO_calender_yearly = data.frame(Year = 2022:2024,
                                    flat = 0,
                                    onpeak = 0,
                                    offpeak = 0)
for(y in 1:3){
  period = paste0(y+2022-1, "A")
  for(j in 1:3){
    peak = peaktype[j]
    result = get.hours("CAISO", peak, period)
    CAISO_calender_yearly[y, j+1] = result$num.hour
    }
  }
print(CAISO_calender_yearly)
```

